"""add_user_audio_cache

Revision ID: 04f753bc6d00
Revises: 2057ea1481b3
Create Date: 2026-07-03 15:01:09.197763
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '04f753bc6d00'
down_revision: Union[str, None] = '2057ea1481b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
