"""add_qa_cache

Revision ID: 2057ea1481b3
Revises: a558150305d7
Create Date: 2026-07-03 14:56:45.898414
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2057ea1481b3'
down_revision: Union[str, None] = 'a558150305d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_progress',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_title', sa.String(length=200), nullable=False),
    sa.Column('book_path', sa.String(length=500), nullable=False),
    sa.Column('total_chapters', sa.Integer(), nullable=False),
    sa.Column('current_chapter', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bp_user_book', 'book_progress', ['user_id', 'book_title'], unique=True)
    op.create_index(op.f('ix_book_progress_user_id'), 'book_progress', ['user_id'], unique=False)
    op.create_table('qa_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_hit_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_qa_mode_hash', 'qa_cache', ['mode', 'question_hash'], unique=True)
    op.create_index(op.f('ix_qa_cache_mode'), 'qa_cache', ['mode'], unique=False)
    op.create_index(op.f('ix_qa_cache_question_hash'), 'qa_cache', ['question_hash'], unique=False)
    op.create_table('user_qa_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('question_hash', sa.String(length=64), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_uqa_user_hash', 'user_qa_cache', ['user_id', 'question_hash'], unique=False)
    op.create_index(op.f('ix_user_qa_cache_user_id'), 'user_qa_cache', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_qa_cache_user_id'), table_name='user_qa_cache')
    op.drop_index('idx_uqa_user_hash', table_name='user_qa_cache')
    op.drop_table('user_qa_cache')
    op.drop_index(op.f('ix_qa_cache_question_hash'), table_name='qa_cache')
    op.drop_index(op.f('ix_qa_cache_mode'), table_name='qa_cache')
    op.drop_index('idx_qa_mode_hash', table_name='qa_cache')
    op.drop_table('qa_cache')
    op.drop_index(op.f('ix_book_progress_user_id'), table_name='book_progress')
    op.drop_index('idx_bp_user_book', table_name='book_progress')
    op.drop_table('book_progress')
    # ### end Alembic commands ###
