"""initial

Revision ID: de7b76e7dd14
Revises: 6acdb05a6b86
Create Date: 2026-07-22 14:57:01.230509
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'de7b76e7dd14'
down_revision: Union[str, None] = '6acdb05a6b86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_phone_unique', table_name='users', postgresql_where='(phone IS NOT NULL)')
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.create_index('ix_users_phone_unique', 'users', ['phone'], unique=True, postgresql_where='(phone IS NOT NULL)')
    # ### end Alembic commands ###
